#!/bin/bash

# Check if $PYFILE variable is set
if [[ -z $PYFILE ]]; then
	echo "Error: Environment variable \$PYFILE is not set."
	exit 1
fi

# Check if the python file exists
if [[ ! -f $PYFILE ]]; then
	echo "Error: Python file '$PYFILE' not found."
	exit 1
fi

python3 $PYFILE
